// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Gegenstand
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public string? Seriennummer { get; set; }

    public int KategorieID { get; set; }

    public int HerstellerID { get; set; }

    public virtual Hersteller Hersteller { get; set; } = null!;

    public virtual Kategorie Kategorie { get; set; } = null!;

    public virtual ICollection<Lagerbewegung> Lagerbewegung { get; set; } = new List<Lagerbewegung>();

    public virtual ICollection<Raumbestand> Raumbestand { get; set; } = new List<Raumbestand>();
}