// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

// Die Validierungsattribute wurden von Hand ergänzt (Maximallängen wie in der Tabelle Gegenstand).
// Achtung: Beim erneuten Generieren mit EF Core Power Tools wird diese Datei überschrieben und die Attribute gehen verloren
public partial class Gegenstand
{
    public int ID { get; set; }

    [Required(ErrorMessage = "Bitte eine Bezeichnung eingeben.")]
    [StringLength(100, ErrorMessage = "Die Bezeichnung darf höchstens {1} Zeichen lang sein.")]
    [Display(Name = "Bezeichnung")]
    public string Name { get; set; } = null!;

    [StringLength(50, ErrorMessage = "Die Seriennummer darf höchstens {1} Zeichen lang sein.")]
    [Display(Name = "Seriennummer")]
    public string? Seriennummer { get; set; }

    [Required(ErrorMessage = "Bitte eine Kategorie auswählen.")]
    [Display(Name = "Kategorie")]
    public int KategorieID { get; set; }

    [Required(ErrorMessage = "Bitte einen Hersteller auswählen.")]
    [Display(Name = "Hersteller")]
    public int HerstellerID { get; set; }

    public virtual Hersteller Hersteller { get; set; } = null!;

    public virtual Kategorie Kategorie { get; set; } = null!;

    public virtual ICollection<Lagerbewegung> Lagerbewegung { get; set; } = new List<Lagerbewegung>();

    public virtual ICollection<Raumbestand> Raumbestand { get; set; } = new List<Raumbestand>();
}