// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Kategorie
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<Gegenstand> Gegenstand { get; set; } = new List<Gegenstand>();
}