// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class LagerverwaltungContext : DbContext
{
    public LagerverwaltungContext()
    {
    }

    public LagerverwaltungContext(DbContextOptions<LagerverwaltungContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bewegungsart> Bewegungsart { get; set; }

    public virtual DbSet<Gegenstand> Gegenstand { get; set; }

    public virtual DbSet<Hersteller> Hersteller { get; set; }

    public virtual DbSet<Kategorie> Kategorie { get; set; }

    public virtual DbSet<Lagerbewegung> Lagerbewegung { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Raum> Raum { get; set; }

    public virtual DbSet<Raumart> Raumart { get; set; }

    public virtual DbSet<Raumbestand> Raumbestand { get; set; }

    public virtual DbSet<Rolle> Rolle { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Lagerverwaltung;Integrated Security=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bewegungsart>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(20);
        });

        modelBuilder.Entity<Gegenstand>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Seriennummer).HasMaxLength(50);

            entity.HasOne(d => d.Hersteller).WithMany(p => p.Gegenstand)
                .HasForeignKey(d => d.HerstellerID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gegenstand_Hersteller");

            entity.HasOne(d => d.Kategorie).WithMany(p => p.Gegenstand)
                .HasForeignKey(d => d.KategorieID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gegenstand_Kategorie");
        });

        modelBuilder.Entity<Hersteller>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Kategorie>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(30);
        });

        modelBuilder.Entity<Lagerbewegung>(entity =>
        {
            entity.Property(e => e.BestaetigtAm).HasColumnType("datetime");
            entity.Property(e => e.ErstelltAm).HasColumnType("datetime");
            entity.Property(e => e.NachRaumID)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.VonRaumID)
                .HasMaxLength(8)
                .IsUnicode(false);

            entity.HasOne(d => d.Bewegungsart).WithMany(p => p.Lagerbewegung)
                .HasForeignKey(d => d.BewegungsartID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lagerbewegung_Bewegungsart");

            entity.HasOne(d => d.Gegenstand).WithMany(p => p.Lagerbewegung)
                .HasForeignKey(d => d.GegenstandID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lagerbewegung_Gegenstand");

            entity.HasOne(d => d.NachRaum).WithMany(p => p.LagerbewegungNachRaum)
                .HasForeignKey(d => d.NachRaumID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lagerbewegung_NachRaum");

            entity.HasOne(d => d.Person).WithMany(p => p.Lagerbewegung)
                .HasForeignKey(d => d.PersonID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lagerbewegung_Person");

            entity.HasOne(d => d.VonRaum).WithMany(p => p.LagerbewegungVonRaum)
                .HasForeignKey(d => d.VonRaumID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lagerbewegung_VonRaum");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nachname).HasMaxLength(250);
            entity.Property(e => e.Password).IsUnicode(false);
            entity.Property(e => e.Username).HasMaxLength(20);
            entity.Property(e => e.Vorname).HasMaxLength(250);

            entity.HasOne(d => d.Rolle).WithMany(p => p.Person)
                .HasForeignKey(d => d.RolleID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Person_Rolle");
        });

        modelBuilder.Entity<Raum>(entity =>
        {
            entity.Property(e => e.ID)
                .HasMaxLength(8)
                .IsUnicode(false);

            entity.HasOne(d => d.Person).WithMany(p => p.Raum)
                .HasForeignKey(d => d.PersonID)
                .HasConstraintName("FK_Raum_Person");

            entity.HasOne(d => d.Raumart).WithMany(p => p.Raum)
                .HasForeignKey(d => d.RaumartID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Raum_Raumart");
        });

        modelBuilder.Entity<Raumart>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(20);
        });

        modelBuilder.Entity<Raumbestand>(entity =>
        {
            entity.HasKey(e => new { e.GegenstandID, e.RaumID });

            entity.Property(e => e.RaumID)
                .HasMaxLength(8)
                .IsUnicode(false);

            entity.HasOne(d => d.Gegenstand).WithMany(p => p.Raumbestand)
                .HasForeignKey(d => d.GegenstandID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Raumbestand_Gegenstand");

            entity.HasOne(d => d.Raum).WithMany(p => p.Raumbestand)
                .HasForeignKey(d => d.RaumID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Raumbestand_Raum");
        });

        modelBuilder.Entity<Rolle>(entity =>
        {
            entity.Property(e => e.Name).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}