// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Lagerbewegung
{
    public int ID { get; set; }

    public int Menge { get; set; }

    public DateTime ErstelltAm { get; set; }

    public DateTime? BestaetigtAm { get; set; }

    public int BewegungsartID { get; set; }

    public string VonRaumID { get; set; } = null!;

    public string NachRaumID { get; set; } = null!;

    public int GegenstandID { get; set; }

    public int PersonID { get; set; }

    public virtual Bewegungsart Bewegungsart { get; set; } = null!;

    public virtual Gegenstand Gegenstand { get; set; } = null!;

    public virtual Raum NachRaum { get; set; } = null!;

    public virtual Person Person { get; set; } = null!;

    public virtual Raum VonRaum { get; set; } = null!;
}