// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Person
{
    public int ID { get; set; }

    public string Vorname { get; set; } = null!;

    public string Nachname { get; set; } = null!;

    public string Username { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string Email { get; set; } = null!;

    public int RolleID { get; set; }

    public virtual ICollection<Lagerbewegung> Lagerbewegung { get; set; } = new List<Lagerbewegung>();

    public virtual ICollection<Raum> Raum { get; set; } = new List<Raum>();

    public virtual Rolle Rolle { get; set; } = null!;
}