// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Raumbestand
{
    public int GegenstandID { get; set; }

    public string RaumID { get; set; } = null!;

    public int Menge { get; set; }

    public virtual Gegenstand Gegenstand { get; set; } = null!;

    public virtual Raum Raum { get; set; } = null!;
}