// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Raumart
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<Raum> Raum { get; set; } = new List<Raum>();
}