// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Raum
{
    public string ID { get; set; } = null!;

    public int? PersonID { get; set; }

    public int RaumartID { get; set; }

    public virtual ICollection<Lagerbewegung> LagerbewegungNachRaum { get; set; } = new List<Lagerbewegung>();

    public virtual ICollection<Lagerbewegung> LagerbewegungVonRaum { get; set; } = new List<Lagerbewegung>();

    public virtual Person? Person { get; set; }

    public virtual Raumart Raumart { get; set; } = null!;

    public virtual ICollection<Raumbestand> Raumbestand { get; set; } = new List<Raumbestand>();
}