// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Lagerverwaltungsapp_MatthiasUtrata.Models;

public partial class Rolle
{
    public int ID { get; set; }

    public string Name { get; set; } = null!;

    public bool Admin { get; set; }

    public virtual ICollection<Person> Person { get; set; } = new List<Person>();
}